import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css';
import 'mapbox-gl/dist/mapbox-gl.css';
import MapProvider from '@/components/context/MapProvider';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Piday Map',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} min-h-screen `}>
        <main>
          <MapProvider>
            {children}
          </MapProvider>
        </main>
      </body>
    </html>
  )
}
